[package]
name = "score_com_concept"
version = "0.1.0"
edition = "2024"

[lib]
path = "../../../../../../info/mwcom/communication/score/mw/com/rust/score_com_concept/lib.rs"

[dependencies]
containers = { path = "../../../../../../info/baselibs/baselibs/score/containers_rust" }
futures = "0.3"
paste = "1"
score_com_macros = { path = "../score_com_macros" }
score_log = { path = "../../../../../../info/baselibs/baselibs/score/log_rust/score_log" }
thiserror = "2"
