# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

COMPILER_WARNING_FEATURES = [
    "treat_warnings_as_errors",
    "strict_warnings",
    "additional_warnings",
]

cc_library(
    name = "common",
    srcs = [
        "algorithms.cpp",
        "error.cpp",
    ],
    hdrs = [
        "algorithms.h",
        "error.h",
    ],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = ["@score_baselibs//score/hash:__subpackages__"],
    deps = [
        "@score_baselibs//score/language/futurecpp",
        "@score_baselibs//score/mw/log",
        "@score_baselibs//score/result",
    ],
)

cc_library(
    name = "common_test",
    srcs = [
        "gtest_printers.cpp",
    ],
    hdrs = [
        "gtest_printers.h",
    ],
    features = COMPILER_WARNING_FEATURES,
    visibility = ["@score_baselibs//score/hash:__subpackages__"],
    deps = [
        ":common",
        "@googletest//:gtest_main",
        "@score_baselibs//score/hash/code/core",
        "@score_baselibs//score/language/futurecpp",
        "@score_baselibs//score/result",
    ],
)

cc_test(
    name = "unit_test",
    srcs = [
        "algorithms_test.cpp",
        "error_test.cpp",
    ],
    features = COMPILER_WARNING_FEATURES,
    tags = ["unit"],
    visibility = ["@score_baselibs//score/hash:__subpackages__"],
    deps = [
        ":common_test",
        "@score_baselibs//score/mw/log:backend_stub_testutil",
        "@score_baselibs//score/mw/log:recorder_mock",
    ],
)
