# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Publish Documentation

on:
  workflow_run:
    workflows: ["CI", "Cache maintenance"]
    types:
      - completed

jobs:
  docs-deploy:
    # In pull requests both the `CI` and `Cache maintenance` workflows are executed,
    # but only `CI` builds documentation in pull requests.
    # Otherwise on pushes to main, the `Cache maintenance` workflow is executed instead and builds the documentation.
    if: >-
      github.event.workflow_run.conclusion == 'success' && !(
        github.event.workflow_run.name == 'Cache maintenance' &&
        github.event.workflow_run.event == 'pull_request'
      )
    uses: eclipse-score/cicd-workflows/.github/workflows/docs-publish.yml@8d80e8df150cae21d53cbc8031d0f970648f7a67 # v.0.0.3
    permissions:
      actions: read
      pages: write
      id-token: write
      contents: write
      pull-requests: write
