# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@rules_cc//cc:defs.bzl", "cc_library")
load("@score_baselibs//:bazel/unit_tests.bzl", "cc_gtest_unit_test")
load("@score_baselibs//score/language/safecpp:toolchain_features.bzl", "COMPILER_WARNING_FEATURES")

cc_library(
    name = "safe_math",
    srcs = ["safe_math.cpp"],
    hdrs = ["safe_math.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = ["//visibility:public"],
    deps = [
        ":error",
        ":return_mode",
        "@score_baselibs//score/language/safecpp/safe_math/details/absolute",
        "@score_baselibs//score/language/safecpp/safe_math/details/addition_subtraction",
        "@score_baselibs//score/language/safecpp/safe_math/details/cast",
        "@score_baselibs//score/language/safecpp/safe_math/details/comparison",
        "@score_baselibs//score/language/safecpp/safe_math/details/division",
        "@score_baselibs//score/language/safecpp/safe_math/details/multiplication",
        "@score_baselibs//score/language/safecpp/safe_math/details/negate",
        "@score_baselibs//score/language/safecpp/safe_math/details/type_traits",
        "@score_baselibs//score/result",
    ],
)

cc_library(
    name = "return_mode",
    srcs = ["return_mode.cpp"],
    hdrs = ["return_mode.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = ["@score_baselibs//score/language/safecpp/safe_math:__subpackages__"],
    deps = ["@score_baselibs//score/result"],
)

cc_library(
    name = "error",
    srcs = ["error.cpp"],
    hdrs = ["error.h"],
    features = COMPILER_WARNING_FEATURES,
    tags = ["FFI"],
    visibility = ["@score_baselibs//score/language/safecpp/safe_math:__subpackages__"],
    deps = ["@score_baselibs//score/result"],
)

cc_gtest_unit_test(
    name = "error_test",
    srcs = ["error_test.cpp"],
    features = COMPILER_WARNING_FEATURES,
    deps = [":error"],
)
