# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

alias(
    name = "stdout_logger_cpp_init",
    actual = "//score/log_rust/stdout_logger_cpp_init:stdout_logger_cpp_init",
    deprecation = "//src/log/stdout_logger_cpp_init:stdout_logger_cpp_init has moved to " +
                  "//score/log_rust/stdout_logger_cpp_init:stdout_logger_cpp_init. " +
                  "Update your dependency to the new //score/... label.",
    visibility = ["//visibility:public"],
)
