module(
    name = "mw_com_provider",
    version = "0.1.0",
)

bazel_dep(name = "rules_rust", version = "0.64.0")
bazel_dep(name = "rules_shell", version = "0.6.1")
bazel_dep(name = "rules_python", version = "1.8.5")
bazel_dep(name = "score_communication", version = "0.0.0")

local_path_override(
    module_name = "score_communication",
    path = "/mnt/c/Shares/ToRutuja/ToPrashanth/communication",
)

rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    edition = "2021",
    versions = ["1.89.0"],
)
use_repo(rust, "rust_toolchains")
register_toolchains("@rust_toolchains//:all")

crate = use_extension("@rules_rust//crate_universe:extension.bzl", "crate")
crate.from_cargo(
    name = "crates",
    cargo_lockfile = "//:Cargo.lock",
    manifests = ["//bazel/cargo:third_party.Cargo.toml"],
)
use_repo(crate, "crates")