# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: chore
      include: scope
    groups:
      github-actions:
        patterns:
          - "*"
          # update-types: not used by intention
          # When using a non-release version of cicd-workflows a lot of PRs will be created by dependabot otherwise

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: chore
      include: scope
    groups:
      cargo:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: chore
      include: scope
    groups:
      pip:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: docker
    directories:
      - /.devcontainer
    schedule:
      interval: daily
    commit-message:
      prefix: chore
      include: scope
    groups:
      docker:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: bazel
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: chore
      include: scope
    groups:
      bazel:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
