load("@rules_cc//cc:cc_binary.bzl", "cc_binary")

cc_binary(
    name = "vehicle_high_beam_remote_app",
    srcs = [
        "high_beam_udp_protocol.h",
        "main.cpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@score_lifecycle//score/launch_manager:lifecycle_cc",
        "@score_logging//score/mw/log:log",
        "@score_persistency//:kvs_cpp",
        "@score_someip_gateway//third_party:vsomeip",
    ],
)
