# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@rules_cc//cc:cc_binary.bzl", "cc_binary")

cc_binary(
    name = "vehicle_high_beam_remote_app",
    srcs = ["main.cpp"],
    visibility = ["//visibility:public"],
    deps = ["@score_someip_gateway//third_party:vsomeip"],
)