# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

"""
This daemon contains the SOME/IP communication stack and is QM
"""

load("@bazel_skylib//rules:native_binary.bzl", "native_binary")
load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

# ============================================================================
# Main Binary
# ============================================================================
cc_binary(
    name = "someipd",
    srcs = ["main.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        ":local_network_service",
        ":remote_network_service",
        ":routing",
        "//score/config:config_flatbuffers",
        "//score/gateway_ipc_binding",
        "//score/socom",
        "@score_baselibs//score/filesystem",
        "@score_lifecycle//score/launch_manager:lifecycle_cc",
        "@score_logging//score/mw/log:log",
        "@score_communication//score/message_passing",
        "@score_communication//score/mw/com",
    ],
)

# ============================================================================
# Libraries
# ============================================================================
cc_library(
    name = "local_network_service",
    srcs = ["impl/local_network_service.cpp"],
    hdrs = ["impl/local_network_service.h"],
    deps = [
        "//score/config:config_flatbuffers",
        "//score/socom",
        "//score/someip",
        "@score_logging//score/mw/log:log",
        "@vsomeip",
    ],
)

cc_library(
    name = "remote_network_service",
    srcs = ["impl/remote_network_service.cpp"],
    hdrs = ["impl/remote_network_service.h"],
    deps = [
        "//score/config:config_flatbuffers",
        "//score/socom",
        "//score/someip",
        "@score_logging//score/mw/log:log",
        "@vsomeip",
    ],
)

cc_library(
    name = "routing",
    srcs = ["impl/routing.cpp"],
    hdrs = ["impl/routing.h"],
    deps = [
        "//score/config:config_flatbuffers",
        "//score/someip",
        "@score_baselibs//score/language/futurecpp",
        "@score_logging//score/mw/log:log",
        "@score_baselibs//score/result",
        "@score_communication//score/mw/com",
        "@vsomeip",
    ],
)

native_binary(
    name = "someipd_example",
    src = "//score/someipd",
    args = [
        "--configuration",
        "$(rootpath //score/config:config_file)",
    ],
    data = [
        "//score/config:config_file",
    ],
)
